import turtle as t
pen = t.Turtle()
t.bgcolor('#00BFFF')
t.delay(8)
pen.color('#FFFFFF')
pen.begin_fill()
pen.left(40)
pen.forward(120)
pen.circle(80, 190)
pen.right(100)
pen.circle(80, 180)
pen.forward(160)
pen.left(90)
pen.forward(50)
pen.setpos(-60, 100)
pen.end_fill()
def txt():
    pen.up()
    pen.setpos(-60, 100)
    pen.color('pink')
    pen.write('I Love Ana', font=("Comic Sans MS", 20))
txt()
pen.end_fill()
t.exitonclick()